/**
 * Machine Identity Module — Collision-Safe ClientID for Client v2 Swarm
 *
 * Purpose:
 *   Every Client v2 instance running on a different host MUST have a unique
 *   CLIENT_ID so Sim Lab's clientsMap tracks them separately without
 *   overwriting each other's telemetry or license state.
 *
 * Strategy (priority order):
 *   1. SHA-256( primaryMAC + apiKeyPrefix ) → "v2-<12 hex chars>"
 *      → Deterministic per machine, survives restarts, no storage needed.
 *   2. If MAC unavailable (VPS / Docker bridge): load from data/identity.json
 *      → Generated once, persisted, stable across restarts.
 *   3. Last resort: random hex string (ephemeral, only if disk is read-only).
 *
 * The generated ID is saved to data/identity.json on first run so that
 * the user and Sim Lab admin can inspect/audit it.
 */

import crypto from 'crypto';
import fs from 'fs';
import os from 'os';
import path from 'path';

const IDENTITY_FILE = path.resolve(process.cwd(), 'data/identity.json');
const ID_PREFIX = 'v3';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns the first real (non-internal, non-virtual) MAC address on the host */
function getPrimaryMac(): string | null {
  try {
    const ifaces = os.networkInterfaces();
    for (const name of Object.keys(ifaces)) {
      // Skip loopback and common virtual adapter names
      const lname = name.toLowerCase();
      if (lname.includes('lo') || lname.includes('virtual') || lname.includes('vmnet') || lname.includes('docker')) {
        continue;
      }
      const addrs = ifaces[name];
      if (!addrs) continue;
      for (const addr of addrs) {
        const mac = addr.mac;
        // Skip null MACs (00:00:00:00:00:00) and loopback
        if (mac && mac !== '00:00:00:00:00:00' && !addr.internal) {
          return mac;
        }
      }
    }
    return null;
  } catch {
    return null;
  }
}

/** SHA-256 hash, returns lowercase hex */
function sha256(input: string): string {
  return crypto.createHash('sha256').update(input, 'utf8').digest('hex');
}

/** Loads a persisted identity file, returns the stored clientId if valid */
function loadPersistedIdentity(): { clientId: string; generatedAt: number } | null {
  try {
    if (fs.existsSync(IDENTITY_FILE)) {
      const raw = fs.readFileSync(IDENTITY_FILE, 'utf8');
      const parsed = JSON.parse(raw);
      if (parsed?.clientId && typeof parsed.clientId === 'string' && parsed.clientId.startsWith(ID_PREFIX + '-')) {
        return parsed;
      }
    }
  } catch { /* unreadable — regenerate */ }
  return null;
}

/** Persists the generated identity to disk for auditability and restart stability */
function persistIdentity(clientId: string, method: string): void {
  try {
    fs.mkdirSync(path.dirname(IDENTITY_FILE), { recursive: true });
    const record = {
      clientId,
      method,
      hostname: os.hostname(),
      platform: os.platform(),
      generatedAt: Date.now(),
      note: 'Auto-generated by Client v2. Do not edit unless migrating to a new machine.',
    };
    fs.writeFileSync(IDENTITY_FILE, JSON.stringify(record, null, 2), 'utf8');
  } catch { /* disk write failed — continue with in-memory ID */ }
}

// ─── Public API ───────────────────────────────────────────────────────────────

export interface MachineIdentity {
  clientId: string;
  /** How the ID was derived — useful for debugging Sim Lab mismatches */
  method: 'mac_hash' | 'persisted_uuid' | 'ephemeral_random';
  /** True if this ID is stable across restarts (mac_hash or persisted_uuid) */
  isStable: boolean;
}

/**
 * Resolves the stable, collision-safe CLIENT_ID for this machine.
 *
 * @param apiKeyHint  First 8 chars of the API key (optional salt — adds
 *                    entropy so two VMs with same MAC on different accounts
 *                    still get different IDs).
 */
export function resolveMachineId(apiKeyHint?: string): MachineIdentity {
  const salt = (apiKeyHint || '').slice(0, 8);
  const mac = getPrimaryMac();

  // ── Strategy 1: MAC-derived deterministic hash ────────────────────────────
  if (mac) {
    const hash = sha256(`${mac}::${salt}`).slice(0, 12);
    const clientId = `${ID_PREFIX}-${hash}`;
    // Persist for audit trail (only if not already saved with same ID)
    const existing = loadPersistedIdentity();
    if (!existing || existing.clientId !== clientId) {
      persistIdentity(clientId, 'mac_hash');
    }
    return { clientId, method: 'mac_hash', isStable: true };
  }

  // ── Strategy 2: Load previously persisted UUID (VPS / Docker) ────────────
  const persisted = loadPersistedIdentity();
  if (persisted) {
    return { clientId: persisted.clientId, method: 'persisted_uuid', isStable: true };
  }

  // ── Strategy 3: Generate new UUID and persist it ──────────────────────────
  const uuid = crypto.randomUUID().replace(/-/g, '').slice(0, 12);
  const clientId = `${ID_PREFIX}-${uuid}`;
  persistIdentity(clientId, 'persisted_uuid');
  return { clientId, method: 'persisted_uuid', isStable: true };
}
